FROM supabase/logflare:1.43.1

# Uncomment to use Big Query backend for analytics (requires gcloud.json service account key from Google Cloud Console)
# COPY ./gcloud.json /opt/app/rel/logflare/bin/gcloud.json