# Envoy override for Kong
# Usage: docker compose -f docker-compose.yml -f docker-compose.envoy.yml up

services:
  # Disable the original Kong service
  kong:
    profiles:
      - disabled

  # Rewire dependencies that require Kong to Envoy
  functions:
    depends_on: !override
      api-gw:
        condition: service_healthy

  # Envoy API gateway
  api-gw:
    container_name: supabase-envoy
    build: ./envoy
    restart: unless-stopped
    ports:
      - ${KONG_PORT}:${KONG_PORT}/tcp
    depends_on:
      studio:
        condition: service_healthy
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY:-}
      SUPABASE_SECRET_KEY: ${SUPABASE_SECRET_KEY:-}
      ANON_KEY_ASYMMETRIC: ${ANON_KEY_ASYMMETRIC:-}
      SERVICE_ROLE_KEY_ASYMMETRIC: ${SERVICE_ROLE_KEY_ASYMMETRIC:-}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      AUTH_HOST: ${AUTH_HOST}
      AUTH_PORT: ${AUTH_PORT}
      REST_HOST: ${REST_HOST}
      REST_PORT: ${REST_PORT}
      REALTIME_HOST: ${REALTIME_HOST}
      REALTIME_PORT: ${REALTIME_PORT}
      STORAGE_HOST: ${STORAGE_HOST}
      STORAGE_PORT: ${STORAGE_PORT}
      FUNCTIONS_HOST: ${FUNCTIONS_HOST}
      FUNCTIONS_PORT: ${FUNCTIONS_PORT}
      META_HOST: ${META_HOST}
      META_PORT: ${META_PORT}
      STUDIO_HOST: ${STUDIO_HOST}
      STUDIO_PORT: ${STUDIO_PORT}
    healthcheck:
      # Using a TCP port check because this image does not include curl or wget.
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/127.0.0.1/8000'"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      default:
        aliases:
          - kong
          - envoy